### ISSUE TITLE
workers.dev域名无法访问

### ISSUE THREAD

**Issue by xihu69** [1234567Yang/cf-proxy-ex#11]
XXX.workers.dev 这个不知道为什么无法访问了，想绑定自己域名，有好像自定义域名只能是Cloudflare 上的域名

y.demo.wvusd.homes
你的这个域名是在Cloudflare 上注册的吗？

**Comment by 1234567Yang** [comment]
Porkbun注册+域名绑定到cf，设置ns，可以自己搜索：绑定域名到clouflare

在 2024年8月2日星期五，xihu69 ***@***.***> 写道：

**Comment by 1234567Yang** [comment]
如果没有问题的话我就关issue了，如果还有问题请描述问题+re-open
