### ISSUE TITLE
安全码不工作

### ISSUE THREAD

**Issue by mouse0232** [1234567Yang/cf-proxy-ex#12]
* **Describe the bug 描述错误**
我设置了password了密码
* **The URL 错误链接**
首页
* **Can you explain/fix it? (can be empty) 您是否能解释错误为何发生/修复错误？（可选）**
`var pwd = getCook(proxyCookie, passwordCookieName);`
这个地方代码好像有问题，应该是如下
`var pwd = getCookpasswordCookieName, siteCookie);`
* **Screenshots (can be empty) 截图（可选）**

* **Additional context (can be empty) 你还要说啥？（可选）**
目前代码如果获取的pwd为空，不管你是否设置密码 都不会403
如果获取的siteCookie为空，不管是否设置密码 都不会403（使用shell的curl 就会必现这个问题，浏览器也会有时候会偶现这个问题）

**Comment by 1234567Yang** [comment]
我是伞兵，commit完忘测试了，等我10分钟

**Comment by 1234567Yang** [comment]
![image](https://github.com/user-attachments/assets/3bb72c78-7860-4195-9b04-d78a6cd91680)
好了，你测试一下

**Comment by 1234567Yang** [comment]
如果还是有BUG的话直接再加comment就好，如果Cookie这个BUG解决了直接close this issue

**Comment by mouse0232** [comment]
测试通过
