### ISSUE TITLE
配置到SwitchyOmega插件中的话，端口号填多少呢

### ISSUE THREAD

**Issue by justwowcq** [1234567Yang/cf-proxy-ex#18]
配置到SwitchyOmega插件中的话，端口号填多少呢？ 
试了8080和80都不行。

**Comment by 1234567Yang** [comment]
没用过这个插件，我不知道怎么设置，但是我这个是在线代理，不是客户端的。
-----
## 有会用的大佬欢迎解释一下

**Comment by 04041b** [comment]
错误用法，close
