### ISSUE TITLE
建议修改这段代码

### ISSUE THREAD

**Issue by eraycc** [1234567Yang/cf-proxy-ex#19]
`if (password != "") {
    if(siteCookie != null && siteCookie != ""){
      var pwd = getCook(passwordCookieName, siteCookie);
      console.log(pwd);
      if (pwd != null && pwd != "") {
        if(pwd != password){
          return getHTMLResponse("<h1>403 Forbidden</h1><br>You do not have access to view this webpage.");
        }
      }else{
        return getHTMLResponse("<h1>403 Forbidden</h1><br>You do not have access to view this webpage.");
      }
    }else{
      return getHTMLResponse("<h1>403 Forbidden</h1><br>You do not have access to view this webpage.");
    }
  }`

建议这些return内容全部修改为：

`<title>无权访问</title><h1>403 Forbidden</h1><br><p>您没有访问该网页的权限！</p><p>请在本页右下角请打开console悬浮窗后输入下面代码并执行∶</p><p>document.cookie = "__PROXY_PWD__=密码";</p><br><p>注意：替换为设置的密码，执行后刷新网页即可正常使用</p><script src="https://s4.zstatic.net/ajax/libs/eruda/3.0.1/eruda.min.js"></script><script>eruda.init();</script>`

这样设置cookie密码后，可以方便在手机或其他设备上使用

**Comment by 1234567Yang** [comment]
可以，思路会借鉴，代码里面可选直接403或者让用户输入密码。

这几周我全都在处理History的问题，History太难搞了

**Comment by Caecilia** [comment]
同感，已提交至pr

**Comment by qingyuan0o0** [comment]
如果用参数的方式加入到url中输入密钥,这样可以让git clone可用?
