### ISSUE TITLE
能否加入安全入口以及能否自动更新cf worker？

### ISSUE THREAD

**Issue by mizb** [1234567Yang/cf-proxy-ex#2]
加入自定义路径。只能通过自定义路径后访问。避免被盗刷

**Comment by mizb** [comment]
已找到设置入口，多谢大佬

**Comment by 1234567Yang** [comment]
你直接设置自己的域名复杂点就好了，比如`a.b.c.d.y.u.i.o.eee.ddd.your_domain.com`，没人能找得到。
或者是自己加上个?pwd=666，然后cf worker里面写一个判断

**Comment by mizb** [comment]
了解。。。大佬，能否支持以下page部署。方便大佬一更新，cf自动更新。。嘻嘻嘻

**Comment by 1234567Yang** [comment]
> 了解。。。大佬，能否支持以下page部署。方便大佬一更新，cf自动更新。。嘻嘻嘻

我记得是可以的，但是只能是自己的账号。那么你可以自己试试fork这个repo，然后链接到cloudflare，具体参考这里：
https://indiehackertools.net/blog/cloudflare-pages-guide-automating-deployment-of-github-projects

因为fork的repo不会自动fetch原来的repo，所以参考这里来实现自动更新你fork的repo：
https://stackoverflow.com/questions/23793062/can-forks-be-synced-automatically-in-github

理论上是可以的。

**Comment by mizb** [comment]
![image](https://github.com/1234567Yang/cf-proxy-ex/assets/22237339/5bc83af5-59bb-4172-a4d4-b9b826356f86)
收尾报错

**Comment by 1234567Yang** [comment]
今天太晚了明天我完整录个视频给你。如果不行的话那么你只能手动cv了……

**Comment by 1234567Yang** [comment]
看了一下，昨天搞错了，抱歉抱歉。应该是没办法自动同步worker，不过你手动cv每月一次也可以啊23333

https://community.cloudflare.com/t/workers-with-github/260819

**Comment by 1234567Yang** [comment]
ok我过几天我会设置cookie安全入口（设置指定cookie key才能用）

**Comment by 1234567Yang** [comment]
已经设置安全入口，详情见readme
