### ISSUE TITLE
能否用于加速 git clone 等类似的操作？

### ISSUE THREAD

**Issue by LiarOnce** [1234567Yang/cf-proxy-ex#20]
如题，如果是单纯自用的情况下可否用于git的各类操作（例如clone，pull，push等）？

**Comment by 1234567Yang** [comment]
![image](https://github.com/user-attachments/assets/acd7f179-0979-400e-9ecc-a71526d89f4d)
```
git clone https://y.demo.wvusd.homes/https://github.com/octocat/Hello-World.git C:\your_dir\1
```

**Comment by LiarOnce** [comment]
仓库地址改了就行，在GitHub Desktop上操作也相当于pull，push指令
