### ISSUE TITLE
大佬能不能支持下CF page部署啊

### ISSUE THREAD

**Issue by HandleBox** [1234567Yang/cf-proxy-ex#23]
* **Your request 你想要啥**

* **Can you just submit a PR? (can be empty) 您是否能~~自己动手，丰衣足食~~（人话：自己提交个PR）？（可选）**

* **Additional context (can be empty) 你还要说啥（可选）**

**Comment by 1234567Yang** [comment]
已经有人问过了，暂不支持
还有就是好奇pages和worker在这个项目里有啥本质上的区别吗，就是好奇

**Comment by HandleBox** [comment]
我说下个人的一些对这两个的部署感受啊，大佬！！！
1.最最最重要的一点就是方便省事；page部署一次，以后升级大佬的代码方便。
2.worker部署升级编辑的时候打开太慢，不方便
以上纯属个人的愚见

**Comment by 1234567Yang** [comment]
> 我说下个人的一些对这两个的部署感受啊，大佬！！！ 1.最最最重要的一点就是方便省事；page部署一次，以后升级大佬的代码方便。 2.worker部署升级编辑的时候打开太慢，不方便 以上纯属个人的愚见

okok我理解了，pages我可能会在完全完全搞定之后再考虑，因为同时维护wokers和pages很容易出错，现在我一个develop version一个正常版本小pr都容易搞错，所以说暂时不支持，但是非常感谢您的指导。

**Comment by 1234567Yang** [comment]
暂时作为重复issue关掉了。
