### ISSUE TITLE
使用失败

### ISSUE THREAD

**Issue by liujiangxu** [1234567Yang/cf-proxy-ex#28]
大佬求救，部署后网站都能打开但是比如在github.com搜索就报错了，google也是页面可以进行下一步就不行了

**Comment by liujiangxu** [comment]
不知道是不是我没设置安全密码导致的？

**Comment by 1234567Yang** [comment]
可能是cf的IP被拉黑了，你能截个Github的图我看看吗？

Google肯定是不能用了，可以用duckduckgo.com代替

至于Github搜索，如果显示"rate limited"可以尝试使用duckduckgo搜索"你的文本" + "site:github.com"
如：`Powertoys site:github.com`

**Comment by liujiangxu** [comment]
![2](https://github.com/user-attachments/assets/c205d327-ce14-4a41-b06b-3735d75eeade)

**Comment by liujiangxu** [comment]
![3](https://github.com/user-attachments/assets/bc9cabef-9923-4bc8-a475-912bd3ac38b2)

**Comment by 1234567Yang** [comment]
Github的可以采用我说的
>duckduckgo搜索"你的文本" + "site:github.com"
>如：Powertoys site:github.com

解决

docker不知道是怎么回事，他们开发者比较闲，JS做了强混淆，还有一堆401和403

**Comment by 1234567Yang** [comment]
具体可以看这里：https://github.com/1234567Yang/cf-proxy-ex/blob/main/usage_tips.md

**Comment by liujiangxu** [comment]
谢谢

**Comment by liujiangxu** [comment]
谢谢
