### ISSUE TITLE
是否会导致域名被GFW防火墙封锁？

### ISSUE THREAD

**Issue by rdself** [1234567Yang/cf-proxy-ex#7]
自己用的话，会被封域名么？如果GFW有手段识别的话，就不敢用自己的域名了😂

**Comment by 1234567Yang** [comment]
<h1>本项目仅供学习使用，严禁从事任何违法违规行为。</h1>
<h3>《中华人民共和国计算机信息网络国际联网管理暂行规定》其中规定了“计算机信息网络直接进行国际联网，必须使用邮电部国家公用电信网提供的国际出入口信道。任何单位和个人不得自行建立或者使用其他信道进行国际联网。</h3>

**Comment by par-nex** [comment]
我见过一个开了两年的国内照常和其它域名一样没被封（有时候红）。这个东西谁都说不准，毕竟我要访问的域名也没加密，网页代理再加密域名有点难，我准备在客户端模式的实现。
但是你又不是整天看那些奇怪的东西，就是加速个Github（Github上某个C开头的可爱除外）。
