### ISSUE TITLE
快速部署cloudflare pages

### ISSUE THREAD

**Issue by Q3dlaXpoaQ** [1234567Yang/cf-proxy-ex#9]
请问作者大大是否能写一个仓库，使得cloudflare pages可以通过git快速部署worker对应的pages。

**Comment by 1234567Yang** [comment]
你是在说：https://github.com/1234567Yang/cf-proxy-ex/issues/8
吗？

目前cf page的worker还好像不支持`//`路径，我已经在community问了，没回

**Comment by Q3dlaXpoaQ** [comment]
> 你是在说：#8 吗？
> 
> 目前cf page的worker还好像不支持`//`路径，我已经在community问了，没回

是的。等待好消息[抱拳]

**Comment by 1234567Yang** [comment]
目前看起来cf page不支持 `xxx.com/xx//xx`，仍在提问。只保留一个issue，可以之后我会提醒你。
